In [ ]:
# Create a 5×5 matrix containing numbers from 1 to 25.
# Extract the third row from a matrix.
# Extract the second column from a matrix.
# Create a NumPy array containing numbers from 1 to 10.
# Create an array of all zeros with 10 elements.
# Create an array of all ones with 15 elements.
# Create an array of even numbers from 2 to 20.
# Create an array of odd numbers from 1 to 19.
# Create a NumPy array and find:
# Shape
# Size
# Data Type
# Number of Dimensions
# Convert the following list into a NumPy array:
# [10, 20, 30, 40, 50]
# Create a NumPy array using linspace() containing 5 values between 0 and 100.
# Create a NumPy array using arange() from 5 to 50 with a step size of 5.
# Create a 3×3 matrix filled with zeros.

In [11]:
import numpy as np
a1=np.array([
                  [1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20],
              [21,22,23,24,25]
              ])
print(a1)
print(a1[2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[11 12 13 14 15]


In [2]:
for i in range(5):
    print(a1[i][1])

2
7
12
17
22


In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a2=np.array([
            [1,2,3,4,5],
            [6,7,8,9,10]
            ])
print(a2.shape)
print(a2.size)
print(a2.ndim)
print(a2.dtype)

(2, 5)
10
2
int64


In [12]:
l1 = [10, 20, 30, 40, 50]
arr = np.array(l1)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [14]:
a3=np.linspace(0,100,5)
a3

array([  0.,  25.,  50.,  75., 100.])

In [15]:
a4=np.arange(5,51,5)
a4

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
a5=np.zeros((3,3))
a5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])